### PR TITLE
Capture calico network policies that drop

### PR DESCRIPTION
**Pull request by kgtw**
Adds functionality to report metrics on calico network-policies that are using `action: Deny`.

Because of the ordering of `iptables-save` output we need to loop over the entire output to build  a mapping of any drop chains and their packet count.

We then loop through for a second time with the original logic, only looking to see if we should use the drop policy packet count if the original return line packet count is 0.

This handles the following scenario, and returns the true packet count of `1164K`

```
Chain cali-po-_iIL2GVSReX3hYOgY4sn (1 references)
 pkts bytes target     prot opt in     out     source               destination
1164K   70M DROP       all  --  *      *       0.0.0.0/0            1.2.3.4/8      /* cali:5MnLDRihpdsyPItp */
```
```
2527K  152M cali-po-_iIL2GVSReX3hYOgY4sn  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:y2OJvPU3e2b4H92l */ mark match 0x0/0x20000
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:IAk_8-dD-Cqt3Gqu */ /* Return if policy accepted */ mark match 0x10000/0x10000
```

### CODE REVIEW

**Comment by jackkleeman** [comment]
@kgtw I wonder should there be a separate metric for packets that are explicitly dropped? Instead of switching between them depending on the value

**Comment by kgtw** [comment]
Yes I think that is best, let me add that now.

**Review by icydoge2 — COMMENTED** [review]
Hi @kgtw, thanks for upstreaming your changes and I'm sorry about the delay in reviewing your PR. Your implementation looks good to us, although I'm slightly worried about the additional performance takeup because of the additional scan loop we do each time. We will probably do some testing on our side. In the meantime, could you bump the version number in https://github.com/monzo/calico-accountant/blob/master/Makefile#L4, e.g. to `v0.1.6`?

**Comment by icydoge2** [comment]
Thank you. I will approve and merge once we've spent some time validating it at runtime.

**Review by icydoge2 — APPROVED** [review]
Validation results look good. Thanks again for upstreaming this.

**Pull request merged**
